defaults:
  - general: train
  - task: hpi-asa
  - mlflow: base
  - datamodule: dischargesummarybert
  - model: dischargesummarybert
  - lightning: base
  - objective: mcc
  - metrics: default
  - evaluate: base
